language: objective-c

xcode_project: RDSActionLabel.xcodeproj
xcode_scheme: RDSActionLabel
osx_image: xcode7.2

script: xctool -workspace RDSActionLabel.xcworkspace -scheme RDSActionLabel clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
