language: objective-c

xcode_project: RDSAnnotatedLabel.xcodeproj
xcode_scheme: RDSAnnotatedLabel
osx_image: xcode7.2

script: xctool -workspace RDSAnnotatedLabel.xcworkspace -scheme RDSAnnotatedLabel clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
