language: objective-c

xcode_project: RDSActionLabel.xcodeproj
xcode_scheme: RDSActionLabel
osx_image: xcode8

before_install:
  - gem install scan

script:
  - scan --workspace "RDSActionLabel.xcworkspace" --scheme "RDSActionLabel" --device "iPhone 6s" --clean
