language: objective-c

xcode_project: RDSActiveLabel.xcodeproj
xcode_scheme: RDSActiveLabel
osx_image: xcode7.2

script: xctool -workspace RDSActiveLabel.xcworkspace -scheme RDSActiveLabel clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
